/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a2deec8f3866cf61445cba84683a9b46)
interface __BaseEnv_Env {
  PAGE_VIEWS_READ_RATE_LIMITER: RateLimit;
  PAGE_VIEWS_WRITE_RATE_LIMITER: RateLimit;
  UPSTASH_REDIS_REST_URL: string;
  UPSTASH_REDIS_REST_TOKEN: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "UPSTASH_REDIS_REST_URL" | "UPSTASH_REDIS_REST_TOKEN">
  > {}
}
